
import { cookies } from "next/headers";
import Navbar from "./component/layout";
import "./globals.css";
import { SocketProvider, UserProvider } from "./context/context";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const cookieStore = cookies();
  const token = cookieStore.get("auth_token")?.value;
  return (
    <html lang="en">
      <body

      >

        {token ? <Navbar /> : null}

        <SocketProvider>


          {children}
        </SocketProvider>

      </body>
    </html>
  );
}
